package com.appdirect.enums;

/**
 * Created by gaurav on 24/12/16.
 */
public enum ErrorCode {
    USER_ALREADY_EXISTS,
    USER_NOT_FOUND,
    ACCOUNT_NOT_FOUND,
    MAX_USERS_REACHED,
    UNAUTHORIZED,
    OPERATION_CANCELED,
    CONFIGURATION_ERROR,
    INVALID_RESPONSE,
    PENDING,
    FORBIDDEN,
    BINDING_NOT_FOUND,
    TRANSPORT_ERROR,
    UNKNOWN_ERROR
}
